### ISSUE TITLE
`isEqual` with empty array as first argument

### ISSUE THREAD

**Issue by jomasti** [arizonatribe/vanillas#1]
Hi, when I was using `isEqual`, I was receiving an unexpected `true` value when trying to compare an empty array to another array.

```js
import isEqual from "vanillas/isEqual";
isEqual([], [1])
```

From looking at the source, it seems to be due to the `.every` usage and `.every` evaluating to `true` for an empty array.

**Comment by arizonatribe** [comment]
Wow, good catch; I completely missed that. I [just patched it](https://github.com/arizonatribe/vanillas/commit/7ecebc226a611230200b342fe74aeda63b038ea7) and added that in as another unit test. Version 0.1.13 that I just published has the fix.

Thanks for spotting this!
