### ISSUE TITLE
Vague types with the new type definitions

### ISSUE THREAD

**Issue by calebfrieze** [arizonatribe/vanillas#10]
Came across a scenario today where I am needing to use `clone()` in TS. The issue I'm seeing is that the generated type definition says that this accepts an `object | object[]` and returns the same. However, this doesn't allow for the implementer to define what kind of object this is, so therefore typescript complains about something not existing on the returned object. 

Example:
https://codesandbox.io/embed/vanillas-clone-example-52nzh?fontsize=14&hidenavigation=1&theme=dark
```
import clone from "vanillas/clone";

const sampleObject: {
  hello: string
} = {
  hello: "world"
}

const something = clone(sampleObject)

console.log(something.hello)
```

In this example, `.hello` does not exist on the type. I think the solution here would be to allow for a generic type. An interface like
```
export default function clone<T>(obj: T | T[]): T | T[]
```
would probably do the trick, however I'm not sure how JSDoc would be able to generate this.

**Comment by arizonatribe** [comment]
Okay just published version 1.5.0 which makes use of generics and overall refines the type definitions. Feel free to re-open this issue if you spot any issues and we'll work through any further refinements to the types. Let me know if you have any other ideas for these types. Thanks Caleb!
